spring:
  application.name: LAA Data Stewardship Access - Access Application Data

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none  # Use Flyway for DB schema.
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

  sql.init.mode: never # Use Flyway for DB schema.

  cloud:
    aws:
      region: ${AWS_REGION}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ENTRA_ISSUER_URI}
          jwk-set-uri: ${ENTRA_JWK_SET_URI}
          audience: ${ENTRA_AUD}

logging:
  level:
    com.azure.spring: INFO
    uk:
      gov:
        justice:
          laa:
            dstew:
              access:
                config:
                  SecurityConfig: WARN

management:
  endpoints.web.exposure.include: health,info,prometheus,metrics
  endpoint.health.show-details: always
  info.env.enabled: true

jdbc:
  datasource-proxy:
    slow-query:
      threshold: ${SLOW_QUERY_THRESHOLD_SECONDS:1}
