openapi: 3.0.0
info:
  title: Generated API from Excel Spec
  version: 1.0.0
paths:
  /api/v2/default-applications:
    post:
      summary: Submit a draft application
      operationId: createDraftApplication
      tags:
        - draftapplication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DraftApplication'
      responses:
        '201':
          description: 'Created'
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '500':
          description: 'Internal server error'

components:
  schemas:
    DraftApplication:
      type: object
      properties:
        application:
          type: object
          properties:
            providerOfficeId:
              type: string
              description: Unique ID of the provider office
            client:
              type: object
              properties:
                individualId:
                  type: string
                  description: Unique client identifier
                employmentStatusCode:
                  type: string
                  description: Employment status code
      required:
        - providerOfficeId