
openapi: 3.0.0
info:
  title: Generated API from Excel Spec
  version: 1.0.0
paths:
  /api/v2/applications/{id}:
    patch:
        tags:
          - application
        summary: Update an application
        operationId: updateApplication
        parameters:
          - name: id
            in: path
            required: true
            description: The id of the application to updated
            schema:
              type: string
              format: uuid
        requestBody:
          description: update an existing item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationUpdateRequest'
        responses:
          '204':
            description: No content
          '400':
            description: 'Bad request'
          '401':
            description: 'Unauthorized'
          '403':
            description: 'Forbidden'
          '404':
            description: 'Not found'
          '500':
            description: 'Internal server error'

    get:
      summary: Get application by id
      operationId: getApplicationById
      tags:
        - application
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the application to retrieve
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'

    delete:
      summary: Delete application by id
      operationId: deleteApplication
      tags:
        - application
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the application to be deleted
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: No content
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'

  /api/v2/applications:
    get:
      tags:
        - application
      summary: Get applications
      operationId: getApplications
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationCollection"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'
    post:
      summary: Submit application
      operationId: createApplication
      tags:
        - application
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationCreateRequest'
      responses:
        '201':
          description: 'Created'
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '500':
          description: 'Internal server error'

components:
  schemas:
    Application:
      type: object
      properties:
        application:
          type: object
          properties:
            providerOfficeId:
              type: string
              description: Unique ID of the provider office
            client:
              type: object
              properties:
                individualId:
                  type: string
                  description: Unique client identifier
                employmentStatusCode:
                  type: string
                  description: Employment status code
                proceedings:
                  type: array
                  items:
                    $ref: "#/components/schemas/ApplicationProceeding"

    ApplicationProceeding:
      properties:
        id:
          type: string
          format: uuid

    ApplicationCollection:
      type: array
      items:
        $ref: "#/components/schemas/Application"

    ApplicationUpdateRequest:
      properties:
        providerOfficeId:
          type: string
          description: Unique ID of the provider office
        client_id:
          type: string
          format: uuid
        status_code:
          type: string
        statement_of_case:
          type: string
        is_emergency_application:
          type: boolean
        proceedings:
          type: array
          items:
            $ref: "#/components/schemas/ApplicationProceedingUpdateRequest"

    ApplicationProceedingUpdateRequest:
      required:
        - proceeding_code
      properties:
        id:
          type: string
          format: uuid
        proceeding_code:
          type: string
        level_of_service_code:
          type: string

    ApplicationCreateRequest:
      type: object
      properties:
        providerOfficeId:
          type: string
          description: Unique ID of the provider office
        application:
          type: object
          properties:
            providerOfficeId:
              type: string
              description: Unique ID of the provider office
            client:
              type: object
              properties:
                individualId:
                  type: string
                  description: Unique client identifier
                employmentStatusCode:
                  type: string
                  description: Employment status code
            proceedings:
              type: array
              items:
                $ref: "#/components/schemas/ApplicationProceedingCreateRequest"

    ApplicationProceedingCreateRequest:
      required:
        - proceeding_code
      properties:
        id:
          type: string
          format: uuid
        proceeding_code:
          type: string
        level_of_service_code:
          type: string
