openapi: "3.0.0"
info:
  title: Applications API
  version: 1.0.0

paths:
  /api/v1/applications/{application-id}/history:
    $ref: "./open-api-application-history-specification.yml#/paths/~1api~1v1~1applications~1{application-id}~1history"
  /api/v1/applications/{application-id}/history/{id}:
    $ref: "./open-api-application-history-specification.yml#/paths/~1api~1v1~1applications~1{application-id}~1history~1{id}"
  /api/v1/applications/{application-id}/history/latest:
    $ref: "./open-api-application-history-specification.yml#/paths/~1api~1v1~1applications~1{application-id}~1history~1latest"
  /api/v2/applications:
    $ref: "./open-api-application-specification.yml#/paths/~1api~1v2~1applications"
  /api/v2/applications/{id}:
    $ref: "./open-api-application-specification.yml#/paths/~1api~1v2~1applications~1{id}"
  /api/v2/draft-applications:
    $ref: "./open-api-draftapplication-specification.yml#/paths/~1api~1v2~1draft-applications"
  /api/v2/draft-applications/{id}:
    $ref: "./open-api-draftapplication-specification.yml#/paths/~1api~1v2~1draft-applications~1{id}"

components:
  schemas:
    ApplicationV1History:
      $ref: "./open-api-specification.yml#/components/schemas/ApplicationV1History"
    ApplicationV1HistoryCreateReq:
      $ref: "./open-api-specification.yml#/components/schemas/ApplicationV1HistoryCreateReq"
    ApplicationV1HistoryCollection:
      $ref: "./open-api-specification.yml#/components/schemas/ApplicationV1HistoryCollection"
    Application:
      $ref: "./open-api-application-specification.yml#/components/schemas/Application"
    ApplicationCreateRequest:
      $ref: "./open-api-application-specification.yml#/components/schemas/ApplicationCreateRequest"
    ApplicationUpdateRequest:
      $ref: "./open-api-application-specification.yml#/components/schemas/ApplicationUpdateRequest"
    ApplicationCollection:
      $ref: "./open-api-application-specification.yml#/components/schemas/ApplicationCollection"
    DraftApplication:
      $ref: "./open-api-draftapplication-specification.yml#/components/schemas/DraftApplication"
