openapi: 3.0.0
info:
  title: Generated API from Excel Spec
  version: 1.0.0
paths:
  /api/v2/applications:
    post:
      summary: Submit application
      operationId: createApplicationV2
      tags:
        - applicationV2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationV2'
      responses:
        '201':
          description: 'Created'
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '500':
          description: 'Internal server error'

components:
  schemas:
    ApplicationV2:
      type: object
      properties:
        application:
          type: object
          properties:
            providerOfficeId:
              type: string
              description: Unique ID of the provider office
            client:
              type: object
              properties:
                individualId:
                  type: string
                  description: Unique client identifier
                employmentStatusCode:
                  type: string
                  description: Employment status code
            applicationProviderUsers:
              type: array
              items:
                type: object
                properties:
                  providerUserId:
                    type: string
                    description: User ID of the provider
                  roleTypeCode:
                    type: string
                    description: Role type such as CONTACT, REVIEWER
            applicationProceedings:
              type: array
              items:
                type: object
                properties:
                  proceedingCode:
                    type: string
                    description: Proceeding code
                  isProceedingConfigDefaulted:
                    type: boolean
                    description: Default scope and cost limitations are used
                  matterTypeCode:
                    type: string
                    description: Matter code
                  categoryOfLawCode:
                    type: string
                    description: Category of law code
                  levelOfServiceCode:
                    type: string
                    description: Level of service code (numeric)
                  stageCode:
                    type: string
                    description: Stage code (numeric)
                  substantiveStartDate:
                    type: string
                    description: Date substantive work starts
                    format: date
                  emergencyStartDate:
                    type: string
                    description: Date emergency work starts
                    format: date
                  scopeLimitations:
                    type: array
                    items:
                      type: object
                      properties:
                        scopeLimitationCode:
                          type: string
                          description: Scope limitation code
                  costLimitationCode:
                    type: number
                    description: Cost limitation code
                  delegatedFunctions:
                    type: object
                    properties:
                      isDelegatedFunctionsUsed:
                        type: boolean
                        description: Whether delegated functions were used
                      delegatedFunctionsNotificationDate:
                        type: string
                        description: Date of delegated function notification
                        format: date
                      delegatedFunctionsUsedDate:
                        type: string
                        description: Date delegated functions were used
                        format: date
            priorAuthorities:
              type: array
              items:
                type: object
                properties:
                  requestTypeCode:
                    type: string
                    description: Type of prior authority request
                  expertType:
                    type: string
                    description: Type of expert
                  requestedAmount:
                    type: number
                    description: Amount requested
                  isIntrospective:
                    type: boolean
                    description: If request is introspective
                  requestedDate:
                    type: string
                    description: Date request was made
                    format: date
                  justification:
                    type: string
                    description: Justification text
            linkedApplications:
              type: array
              items:
                type: object
                properties:
                  linkedApplicationId:
                    type: string
                    description: Linked application identifier
                    format: uuid
                  linkTypeCode:
                    type: string
                    description: Link type code
                  linkTypeSubCode:
                    type: string
                    description: Link type subcode
            evidences:
              type: array
              items:
                type: object
                properties:
                  sdsUniqueId:
                    type: string
                    description: Unique SDS Id for the document evidence
                    format: uuid
                  evidenceTypeCode:
                    type: string
                    description: Type of evidence, e.g. Prior authority, statement of case, certificate etc
                  linkedDocumentId:
                    type: string
                    description: Linked document ID - the specific id of the document, i.e. application id, merits assessment id, amendment id
                  linkedDocumentTypeCode:
                    type: string
                    description: Type of linked document e.g. application, merits, assessment, amendment, appeal etc
            assessments:
              type: array
              items:
                type: object
                properties:
                  assessmentId:
                    type: number # TBC
                    description: The ID of the assessment that was completed. This could be means or merits
                  assessmentTypeCode:
                    type: string
                    description: ""
                  individualId:
                    type: number # TBC
                    description: ""
                  amendmentId:
                    type: number # TBC
                    description: ""
                  appealId:
                    type: number #TBC
                    description: ""
                  meansAssessment:
                    type: object
                    properties: {}
                    description: ""
                  meritsAssessment:
                    type: object
                    properties: {}
                    description: ""
            interestedParties:
              type: array
              items:
                type: object
                properties:
                  individualId:
                    type: number # TBC
                    description: ""
                  organizationId: # TBC
                    type: number
                    description: ""
                  fullName:
                    type: string
                    description: ""
                  dateOfBirth:
                    type: string
                    description: ""
                    format: date
                  partyType:
                    type: string
                    description: ""
                  interestTypeCode:
                    type: string
                    description: ""
      required:
        - providerOfficeId