openapi: 3.0.0
info:
  title: Generated API from Excel Spec
  version: 1.0.0
paths:
  /api/v2/draft-applications:
    post:
      summary: Submit a draft application
      operationId: createDraftApplication
      tags:
        - draftapplication
      requestBody:
        description: create a draft application
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DraftApplicationCreateReq'

      responses:
        '201':
          description: 'Created'
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '500':
          description: 'Internal server error'

components:
  schemas:
    DraftApplication:
      type: object
      additionalProperties: true
      properties:
            id:
              type: string
              format: uuid
              description: Unique ID of the application
            client_id:
              type: string
              format: uuid
              description: Unique client identifier
            provider_id:
              type: string
              format: uuid
              description: Unique ID of the provider
    DraftApplicationCreateReq:
      type: object
      additionalProperties: true
      properties:
        provider_id:
          type: string
          format: uuid
        client_id:
          type: string
          format: uuid
