#!/bin/bash
set -e

filesToFormat="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.java/ { print $NF}')"

echo "files to format $filesToFormat"
for sourceFilePath in $filesToFormat
do
  ./gradlew spotlessApply -PspotlessIdeHook="$(pwd)/$sourceFilePath"
  git add $sourceFilePath
done;

./gradlew checkStyleMain
## readd these once we've taken the time to fix the checkStyle errors (build only just main, test/integrationTest don't run the checkstyle
##./gradlew checkStyleTest
##./gradlew checkStyleIntegrationTest