apiVersion: v1
kind: ConfigMap
metadata:
  name: mock-oauth2-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: mock-oauth2-server
    helm.sh/chart: {{ include "data-access-api.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.json: |
    {
      "interactiveLogin": false,
      "tokenCallbacks": [
        {
          "issuerId": "entra",
          "tokenExpiry": 3600,
          "requestMappings": [
            {
              "requestParam": "grant_type",
              "match": "client_credentials",
              "claims": {
                "sub": "test-user",
                "aud": ["laa-data-access-api"],
                "roles": ["LAA_CASEWORKER"],
                "LAA_APP_ROLES": "LAA_CASEWORKER"
              }
            }
          ]
        }
      ]
    }

