apiVersion: v1
kind: Service
metadata:
  name: mock-oauth2-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: mock-oauth2-server
    helm.sh/chart: {{ include "data-access-api.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: mock-oauth2-server
  ports:
    - name: http
      port: 9999
      targetPort: 9999
      protocol: TCP
