openapi: "3.0.0"
info:
  title: Applications API
  version: 1.0.0

paths:
  /api/v0/applications:
    $ref: "./open-api-application-specification.yml#/paths/~1api~1v0~1applications"
  /api/v0/applications/{id}:
    $ref: "./open-api-application-specification.yml#/paths/~1api~1v0~1applications~1{id}"
  /api/v0/caseworkers:
    $ref: "./open-api-application-specification.yml#/paths/~1api~1v0~1caseworkers"
  /api/v0/applications/assign:
    $ref: "./open-api-application-specification.yml#/paths/~1api~1v0~1applications~1assign"
  /api/v0/applications/{id}/unassign:
    $ref: "./open-api-application-specification.yml#/paths/~1api~1v0~1applications~1{id}~1unassign"

components:
  schemas:
    Application:
      $ref: "./open-api-application-specification.yml#/components/schemas/Application"
    ApplicationCreateRequest:
      $ref: "./open-api-application-specification.yml#/components/schemas/ApplicationCreateRequest"
    ApplicationUpdateRequest:
      $ref: "./open-api-application-specification.yml#/components/schemas/ApplicationUpdateRequest"
    ApplicationSummaryResponse:
      $ref: "./open-api-application-specification.yml#/components/schemas/ApplicationSummaryResponse"
    ApplicationSummary:
      $ref: "./open-api-application-specification.yml#/components/schemas/ApplicationSummary"
    Caseworker:
      $ref: "./open-api-application-specification.yml#/components/schemas/Caseworker"
    CaseworkerResponse:
      $ref: "./open-api-application-specification.yml#/components/schemas/CaseworkerResponse"
    CaseworkerAssignRequest:
      $ref: "./open-api-application-specification.yml#/components/schemas/CaseworkerAssignRequest"
    DomainEvent:
      $ref: "./open-api-application-specification.yml#/components/schemas/DomainEvent"