openapi: "3.0.0"
info:
  title: Applications API
  version: 1.0.0

paths:
  /api/v0/applications:
    $ref: "./open-api-application-specification.yml#/paths/~1api~1v0~1applications"
  /api/v0/applications/{id}:
    $ref: "./open-api-application-specification.yml#/paths/~1api~1v0~1applications~1{id}"
  /api/v1/applications:
    $ref: "./open-api-application-specification.yml#/paths/~1api~1v1~1applications"

components:
  schemas:
    Application:
      $ref: "./open-api-application-specification.yml#/components/schemas/Application"
    ApplicationCreateRequest:
      $ref: "./open-api-application-specification.yml#/components/schemas/ApplicationCreateRequest"
    ApplicationUpdateRequest:
      $ref: "./open-api-application-specification.yml#/components/schemas/ApplicationUpdateRequest"
    ApplicationSummaryCollection:
      $ref: "./open-api-application-specification.yml#/components/schemas/ApplicationSummaryCollection"
    ApplicationSummary:
      $ref: "./open-api-application-specification.yml#/components/schemas/ApplicationSummary"