openapi: "3.0.0"
info:
  version: 1.0.0
  title: Apply Application V1

components:
  schemas:
    applyApplication:
      allOf:
        - $ref: '../common/open-api-application-content-common.yml#/components/schemas/ApplicationContentBase'
      additionalProperties: true