name: "Deploy branch"
description: 'Deploy docker image of branch to namespace with an ingress based on branch name'
inputs:
  ecr-repository:
    description: "ECR repository"
    required: true
  ecr-region:
    description: "ECR region"
    required: true
  ecr-role-to-assume:
    description: "ECR role to assume"
    required: true
  kube-cert:
    description: "Kubernetes cluster authentication certificate"
    required: true
  kube-token:
    description: "Kubernetes cluster authentication token"
    required: true
  kube-cluster:
    description: "Kubernetes cluster name"
    required: true
  kube-namespace:
    description: "Kubernetes cluster namespace"
    required: true
  app-environment:
    description: "environment to which the app is being deployed [staging, production, etc]"
    required: true
  pr-number:
    description: "Pull request number. When provided, release name will be pr-{number}."
    required: false
  image-tag:
    description: "Docker image tag to deploy. Defaults to the git SHA."
    required: false
    default: ${{ github.sha }}

outputs:
  branch-name:
    description: "Extracted branch name"
    value: ${{ steps.extract_release_name.outputs.branch-name }}
  release-name:
    description: "Extracted release name"
    value: ${{ steps.extract_release_name.outputs.release-name }}

runs:
  using: "composite"
  steps:

    - name: Extract release name
      id: extract_release_name
      uses: ./.github/actions/get_release_name
      with:
        pr-number: ${{ inputs.pr-number }}

    - name: Run deploy prerequisites
      id: deploy_prerequisites
      uses: ./.github/actions/deploy_prerequisites
      with:
        kube-cert: ${{ inputs.kube-cert }}
        kube-token: ${{ inputs.kube-token }}
        kube-cluster: ${{ inputs.kube-cluster }}
        kube-namespace: ${{ inputs.kube-namespace }}
        ecr-role-to-assume: ${{ inputs.ecr-role-to-assume }}
        ecr-region: ${{ inputs.ecr-region }}

    - name: Get LAA IP allowlist
      id: get_laa_ips
      uses: ./.github/actions/get_laa_ips

    - name: Deploy preview PostgreSQL
      if: ${{ steps.extract_release_name.outputs.branch-name != 'main' }}
      uses: ./.github/actions/deploy_ephemeral_postgres
      with:
        release-name: ${{ steps.extract_release_name.outputs.release-name }}
        kube-namespace: ${{ inputs.kube-namespace }}
        values-file: .helm/bitnami_postgres/values.yaml
        cleanup-stale-pvc: "true"

    - name: Helm deployment of branch
      shell: bash
      env:
        ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        ECR_REGION: ${{ inputs.ecr-region }}
        ECR_REGISTRY: ${{ steps.deploy_prerequisites.outputs.ecr-registry }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        KUBE_NAMESPACE: ${{ inputs.kube-namespace }}
        VALUES_FILE: .helm/data-access-api/values/${{ inputs.app-environment }}.yaml
        RELEASE_NAME: ${{ steps.extract_release_name.outputs.release-name }}
        BRANCH_NAME: ${{ steps.extract_release_name.outputs.branch-name }}
        LAA_IPS: ${{ steps.get_laa_ips.outputs.laa-ips }}
        APP_ENVIRONMENT: ${{ inputs.app-environment }}
      run: |
        ingress_name="$RELEASE_NAME-data-access-api"
        external_host="$RELEASE_NAME-$KUBE_NAMESPACE.cloud-platform.service.justice.gov.uk"
        internal_host="$RELEASE_NAME-internal-$KUBE_NAMESPACE.internal-non-prod.cloud-platform.service.justice.gov.uk"
        external_identifier="$ingress_name-$KUBE_NAMESPACE-green"
        internal_identifier="$RELEASE_NAME-data-access-api-internal-$KUBE_NAMESPACE-green"
        branch_name="$BRANCH_NAME"

        echo "Deploying commit: $GIT_SHA under release name: $RELEASE_NAME to $external_host and $internal_host..."

        echo "branch name: $branch_name"

        if [ "$branch_name" == "main" ]; then
          case "$APP_ENVIRONMENT" in
            production)
              export SPRING_PROFILE="main"
              ;;
            *)
              export SPRING_PROFILE="unsecured"
              ;;
          esac
        else
          export SPRING_PROFILE="preview"
        fi
        

        helm upgrade $RELEASE_NAME .helm/data-access-api \
          --namespace ${KUBE_NAMESPACE} \
          --set image.repository="${ECR_REGISTRY}/${ECR_REPOSITORY}" \
          --set image.tag="${IMAGE_TAG}" \
          --set ingress.annotations."external-dns\.alpha\.kubernetes\.io/set-identifier"="$external_identifier" \
          --set ingress.annotations."nginx\.ingress\.kubernetes\.io/whitelist-source-range"="$LAA_IPS" \
          --set ingress.hosts="{$external_host}" \
          --set ingressInternal.annotations."external-dns\.alpha\.kubernetes\.io/set-identifier"="$internal_identifier" \
          --set ingressInternal.hosts="{$internal_host}" \
          --set spring.profile="${SPRING_PROFILE}" \
          --set aws.region="${ECR_REGION}" \
          --set autoscaling.enabled="$([ "$branch_name" = "main" ] && echo true || echo false)" \
          --values ${VALUES_FILE} \
          --install \
          --wait

        helm upgrade ${RELEASE_NAME}-mass-generator .helm/mass-generator \
          --namespace ${KUBE_NAMESPACE} \
          --set image.repository="${ECR_REGISTRY}/${ECR_REPOSITORY}" \
          --set image.tag="${IMAGE_TAG}-mass-generator" \
          --set spring.profile="${SPRING_PROFILE}" \
          --set db.postgresqlReleaseName="${RELEASE_NAME}-postgresql" \
          --install \
          --wait

