services:
  postgres:
    image: postgres:17
    mem_limit: 16834m        # limit RAM to 512 MB
    cpus: 4
    container_name: laa-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laa_data_access_api
      POSTGRES_USER: laa_user
      POSTGRES_PASSWORD: laa_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: laa-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:13.1.0
    container_name: laa-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro

  localstack:
    image: localstack/localstack:3.6.0
    ports:
      - "4566:4566" # LocalStack edge service (all services)
      - "4510-4559:4510-4559" # additional ports used by some services (optional)
    environment:
      - SERVICES=s3,dynamodb
      - PERSISTENCE=1 # persist data across container restarts
      - DEFAULT_REGION=eu-west-2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_VOLUME_DIR=/var/lib/localstack
      - DYNAMODB_SHARE_DB=1 # share DynamoDB data across multiple LocalStack instances (optional)
    volumes:
      - localstack_state:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts:/etc/localstack/init/ready.d:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  localstack_state:
