services:
  postgres:
    image: postgres:17
    container_name: laa-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laa_data_access_api
      POSTGRES_USER: laa_user
      POSTGRES_PASSWORD: laa_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  wiremock:
    image: wiremock/wiremock:4.0.0-beta.29
    container_name: laa-wiremock
    restart: unless-stopped
    ports:
      - "8181:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings:ro
      - ./wiremock/__files:/home/wiremock/__files:ro
    command: --verbose

volumes:
  pgdata: