name: Preview Install
description: Install a preview app into the uat namespace
inputs:
  image:
    description: Docker image URL to deploy (e.g. registry/repository)
    required: true
  tag:
    description: Docker image tag to deploy (e.g. 1.2.3 or pr-123-d2a094ef)
    required: true
  preview:
    description: Name of the preview app (Helm release name, e.g. pr-123)
    required: true

runs:
  using: composite
  steps:
    - name: Upgrade Helm chart
      shell: bash
      run: |
        set -euo pipefail
        echo "Upgrade Helm chart - image: [${{ inputs.image }}], tag: [${{ inputs.tag }}], preview: [${{ inputs.preview }}]"
        IP_ALLOWLIST="$(kubectl get secret app-secrets -o json | jq -r '.data["IP_ALLOWLIST"] | @base64d')"
        PREVIEW_HOST="laa-data-access-api-${{ inputs.preview }}.apps.cloud-platform.service.justice.gov.uk"
        HELM_OPTS=( \
            -f "./helm_deploy/data-access-service/values.yaml"
            -f "./helm_deploy/data-access-service/values-uat.yaml"
            --set previewDeploy=true \
            --set-string "image.repository=${{ inputs.image }}" \
            --set-string "image.tag=${{ inputs.tag }}" \
            --set internalIngress.enabled=false \
            --set-string "ingress.allowlist=${IP_ALLOWLIST//,/\\,}" \
            --set-string "ingress.hosts[0].host=${PREVIEW_HOST}" \
            --set-string "ingress.tls[0].hosts[0]=${PREVIEW_HOST}" \
        )
        helm upgrade --install "${{ inputs.preview }}" "./helm_deploy/data-access-service" "${HELM_OPTS[@]}" --debug --dry-run=server
        # If the dry-run succeeded, do the real thing
        helm upgrade --install "${{ inputs.preview }}" "./helm_deploy/data-access-service" "${HELM_OPTS[@]}"
