apiVersion: v1
kind: Service
metadata:
  name: mock-oauth2-server
  labels:
    app: mock-oauth2-server
spec:
  type: ClusterIP
  selector:
    app: mock-oauth2-server
  ports:
    - name: http
      port: 9999
      targetPort: 9999
      protocol: TCP
