CREATE TABLE IF NOT EXISTS caseworker(
    ID UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT(NOW() AT TIME ZONE 'UTC'),
    modified_at TIMESTAMPTZ NOT NULL DEFAULT(NOW() AT TIME ZONE 'UTC'),
    username VARCHAR NOT NULL,
    CONSTRAINT caseworker_pkey PRIMARY KEY (ID)
);