spring:
  application:
    name: LAA Data Access Mass Generator

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/laa_data_access_api?reWriteBatchedInserts=true}
    username: ${SPRING_DATASOURCE_USERNAME:laa_user}
    password: ${SPRING_DATASOURCE_PASSWORD:laa_password}

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

  sql:
    init:
      mode: never

  flyway:
    enabled: false

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: WARN
    uk.gov.justice.laa.dstew.access.massgenerator: INFO

