name: "Get merged release name"
description: 'Get the release name for the PR that has just been closed or merged into Main branch'

outputs:
  merged-branch-name:
    description: "Extracted merged branch name"
    value: ${{ steps.get_release_name.outputs.BRANCH_NAME }}
  release-name-to-delete:
    description: "Extracted merged release name"
    value: ${{ steps.get_release_name.outputs.release_name }}

runs:
  using: "composite"
  steps:

    - name: Get release name to delete
      id: get_release_name
      shell: bash
      env:
        EVENT_NAME: ${{ github.event_name }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        EVENT_REF: ${{ github.event.ref }}
      run: |
        if [[ "$EVENT_NAME" == "pull_request" ]]; then
          echo "BRANCH_NAME=$PR_HEAD_REF" >> $GITHUB_OUTPUT
          echo "release_name=pr-${PR_NUMBER}" >> $GITHUB_OUTPUT
        elif [[ "$EVENT_NAME" == "delete" ]]; then
          echo "BRANCH_NAME=$EVENT_REF" >> $GITHUB_OUTPUT
          release_name=$(echo "$EVENT_REF" | tr '[:upper:]' '[:lower:]' | tr -s ' _/[]().' '-' | cut -c1-15 | sed 's/-$//')
          echo "release_name=${release_name}" >> $GITHUB_OUTPUT
        fi
