apiVersion: v2
name: data-access-api-axon
description: A Helm chart for the LAA Data Access Axon (CQRS) service

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed.
appVersion: "0.1.0"

