replicaCount: 0

image:
  repository: null
  tag: null

serviceAccountName: null

spring:
  profile: preview

resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 25m
    memory: 512Mi

