{{/*
serviceaccount.yaml (not used)
Creates a service account.
*/}}
{{ if (.Values.serviceAccount).create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "providers-app.serviceAccountName" . }}
  labels:
    {{- include "providers-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
