spring:
  jpa:
    hibernate:
      ddl-auto: create-drop  # Create schema for integration tests
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: never  # Don't use SQL scripts, rely on Hibernate schema generation for tests

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
feature:
  disable-security: true
