spring:
  application.name: LAA Access Data Stewardship API

  datasource:
    url: jdbc:postgresql://localhost:5432/laa_db
    username: laa_user
    password: laa_password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none  # Use Flyway for DB schema.

  sql.init.mode: never # Use Flyway for DB schema.

  cloud:
    aws:
      region.static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs.endpoint: http://localhost:4566

    azure:
      active-directory:
        profile.tenant-id: ${ENTRA_TENANT_ID}
        app-id-uri: ${ENTRA_APP_ID_URI}

info:
  app:
    name: Access
    description: LAA Access Data Stewardship REST API
    version: 1.0.0

logging:
  level:
    com.azure.spring: INFO

management:
  endpoints.web.exposure.include: health,info
  endpoint.health.show-details: always
  info.env.enabled: true

### Set feature flags in the environment to avoid committing insecure values.
### For example, `FEATURE_SECURITY=false` to disable endpoint authorization,
### or `FEATURE_TRANSFORMATION=false` to disable response transformations.

#feature:
#  security: true
#  transformation: true
