plugins {
    id 'application'
}

application {
    mainClass = 'uk.gov.justice.laa.dstew.dataaccesstools.cli.DataAccessToolsCommand'
    applicationName = 'data-access-tools'
}

dependencies {
    implementation 'info.picocli:picocli:4.7.7'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.13.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}


