name: Snyk Scan

inputs:
  token:
    required: true
    description: "Snyk token"
runs:
  using: 'composite'

  steps:
    - name: Setup Snyk CLI
      uses: snyk/actions/setup@master

    - name: Run Snyk scan
      run: snyk test -d --all-projects --severity-threshold=high --sarif-file-output=snyk.sarif --exclude=[access-datastore-api/generated/pom.xml]
      env:
        SNYK_TOKEN: ${{ inputs.token }}
      shell: bash