image:
  repository: null
  tag: null

spring:
  profile: preview

db:
  postgresqlReleaseName: null

job:
  recordCount: 200

resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 25m
    memory: 512Mi
