spring:
  application.name: data-access-service-axon

  datasource:
    url: ${DB_URL}
    username: "postgres"
    password: ${DB_PASSWORD}

  jpa:
    database-platform: uk.gov.justice.laa.dstew.access.config.ByteaEnforcedPostgresSqlDialect
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${AXON_DB_SCHEMA:axon}

  sql.init.mode: never # Use Flyway for DB schema.

  cloud:
    aws:
      region: ${AWS_REGION}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ENTRA_ISSUER_URI}
          jwk-set-uri: ${ENTRA_JWK_SET_URI}
          audience: ${ENTRA_AUD}

axon:
  db:
    schema: ${AXON_DB_SCHEMA:axon}
    flyway-table: ${AXON_FLYWAY_TABLE:flyway_schema_history}

logging:
  level:
    com.azure.spring: INFO
    uk:
      gov:
        justice:
          laa:
            dstew:
              access:
                config:
                  SecurityConfig: WARN

management:
  endpoints.web.exposure.include: health,info,prometheus,metrics
  endpoint.health.show-details: always
  info.env.enabled: true
