server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: data-access-service-axon
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/laa_data_access_api?currentSchema=axon}
    username: ${SPRING_DATASOURCE_USERNAME:laa_user}
    password: ${SPRING_DATASOURCE_PASSWORD:laa_password}
  flyway:
    create-schemas: true
    default-schema: axon
    schemas: axon
  jpa:
    properties:
      hibernate:
        default_schema: axon

axon:
  axonserver:
    enabled: false
  converter:
    general: jackson
    events: jackson
    messages: jackson

application:
  projection:
    timeout: 5s

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  api-docs:
    version: openapi_3_1
