name: Build and run tests
description: Build and run tests

inputs:
  user:
    required: true
    description: "user account"
  token:
    required: true
    description: "Github token"

runs:
  using: "composite"

  steps:
    - name: Gradle build
      id: build_and_test
      run: ./gradlew build
      env:
        GITHUB_ACTOR: ${{ inputs.user}}
        GITHUB_TOKEN: ${{ inputs.token }}
      shell:
        bash