apiVersion: apps/v1
kind: Deployment
metadata:
  name: laa-data-access-api-deployment
  labels:
    app: laa-data-access-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: laa-data-access-api-pod
  template:
    metadata:
      labels:
        app: laa-data-access-api-pod
    spec:
      containers:
        - name: laa-data-access-api-container
          image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - containerPort: 8081
          env:
          - name: db_identifier
              valueFrom: 
                secretKeyRef: 
                  name: rds-postgresql-instance-output
                  key: db_identifier
            - name: rds_instance_address
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: rds_instance_address 
            - name: rds_instance_endpoint
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: rds_instance_endpoint
            - name: rds_instance_port
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key:  rds_instance_port
            - name: database_name
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_name
            - name: database_username
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_username
            - name: database_password
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_password
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10001
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /actuator/health/
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3