apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mass-generator
  labels:
    app.kubernetes.io/name: mass-generator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: mass-generator
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mass-generator
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mass-generator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          command: ["sleep", "infinity"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if eq .Values.spring.profile "preview" }}
            - name: DB_NAME
              value: "postgres"
            - name: DB_HOST
              value: {{ .Release.Name }}-postgresql
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgres-password
            {{- else }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: rds_instance_address
            {{- end }}
            - name: DB_URL
              value: "jdbc:postgresql://$(DB_HOST):5432/$(DB_NAME)"
