name: Build feature

on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-publish-snapshot:
    uses: ./.github/workflows/gradle-build-and-publish.yml
    permissions:
      contents: write
      packages: write
    with:
      publish_package: 'true'
      is_snapshot: 'true'
      checkstyle_report: 'false'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}