name: Build feature

on:
  push:
    branches-ignore:
      - main
      - 'feature-dev/*'
      - 'feature-test/*'


jobs:
  build-and-publish-snapshot:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@v1
    permissions:
      contents: write
      packages: write
    with:
      integration_test_task: ""
      publish_package: 'true'
      is_snapshot: 'true'
      junit_results_path: 'dstew-access-service/build/test-results'
      junit_report_path: 'dstew-access-service/build/reports/tests'
      checkstyle_report_path: 'dstew-access-service/build/reports/checkstyle'
      jacoco_coverage_report: 'false'
      jacoco_coverage_report_path: 'dstew-access-service/build/reports/jacoco'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
