name: Build feature

on:
  push:
    branches-ignore:
      - main
        
jobs:
  setup-containers:
    run: docker compose up -d

  build-and-publish-snapshot:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@v1
    permissions:
      contents: write
      packages: write
    with:
      publish_package: 'true'
      is_snapshot: 'true'
      checkstyle_report: 'false'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}