name: Code Coverage

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      packages: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Make Gradle Wrapper Executable
        run: chmod +x gradlew

      - name: Run Tests and Generate Aggregated Report
        run: ./gradlew clean build jacocoAggregatedReport --continue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Report to PR Comment
        uses: madrapps/jacoco-report@v1.6.1
        with:
          path: build/reports/jacoco/aggregated.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'JaCoCo Code Coverage Report'
          min-coverage-overall: 60
          min-coverage-changed-files: 70