name: Deployment Pipeline
permissions:
  contents: write
  packages: read
  id-token: write
  security-events: write

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  dev-deployment:
    name: Dev deployment
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reusable-deployment.yml
    with:
      environment: dev
      environment-prefix: Dev
      ecr-repository: DEV_ECR_REPOSITORY
      ecr-region: DEV_ECR_REGION
      branch-name: main
      prometheus_severity: laa-provider-data-api-alerts-nonprod
      spring_profile: dev
    secrets:
      ecr-role-to-assume: ${{ secrets.DEV_ECR_ROLE_TO_ASSUME }}
      kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
      kube_cluster: ${{ secrets.KUBE_CLUSTER }}
      kube_token: ${{ secrets.KUBE_TOKEN }}
      kube_cert: ${{ secrets.KUBE_CERT }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
      GITHUBAPP_ID: ${{ secrets.GITHUBAPP_ID }}
      GITHUBAPP_PRIVATE_KEY: ${{ secrets.GITHUBAPP_PRIVATE_KEY }}

  uat-deployment:
    name: UAT deployment
    needs: dev-deployment
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reusable-deployment.yml
    with:
      environment: uat
      environment-prefix: Uat
      ecr-repository: UAT_ECR_REPOSITORY
      ecr-region: UAT_ECR_REGION
      branch-name: main
      prometheus_severity: laa-provider-data-api-alerts-nonprod
      spring_profile: uat
    secrets:
      ecr-role-to-assume: ${{ secrets.UAT_ECR_ROLE_TO_ASSUME }}
      kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
      kube_cluster: ${{ secrets.KUBE_CLUSTER }}
      kube_token: ${{ secrets.KUBE_TOKEN }}
      kube_cert: ${{ secrets.KUBE_CERT }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
      GITHUBAPP_ID: ${{ secrets.GITHUBAPP_ID }}
      GITHUBAPP_PRIVATE_KEY: ${{ secrets.GITHUBAPP_PRIVATE_KEY }}

  preprod-deployment:
    name: Preprod deployment
    needs: uat-deployment
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reusable-deployment.yml
    with:
      environment: preprod
      environment-prefix: Preprod
      ecr-repository: PREPROD_ECR_REPOSITORY
      ecr-region: PREPROD_ECR_REGION
      branch-name: main
      prometheus_severity: laa-provider-data-api-alerts-nonprod
      spring_profile: preprod
    secrets:
      ecr-role-to-assume: ${{ secrets.PREPROD_ECR_ROLE_TO_ASSUME }}
      kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
      kube_cluster: ${{ secrets.KUBE_CLUSTER }}
      kube_token: ${{ secrets.KUBE_TOKEN }}
      kube_cert: ${{ secrets.KUBE_CERT }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
      GITHUBAPP_ID: ${{ secrets.GITHUBAPP_ID }}
      GITHUBAPP_PRIVATE_KEY: ${{ secrets.GITHUBAPP_PRIVATE_KEY }}

  prod-deployment:
    name: Prod deployment
    needs: preprod-deployment
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reusable-deployment.yml
    with:
      environment: prod
      environment-prefix: Prod
      ecr-repository: PROD_ECR_REPOSITORY
      ecr-region: PROD_ECR_REGION
      branch-name: main
      prometheus_severity: laa-provider-details-api-alerts-prod
      spring_profile: prod
    secrets:
      ecr-role-to-assume: ${{ secrets.PROD_ECR_ROLE_TO_ASSUME }}
      kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
      kube_cluster: ${{ secrets.KUBE_CLUSTER }}
      kube_token: ${{ secrets.KUBE_TOKEN }}
      kube_cert: ${{ secrets.KUBE_CERT }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
      GITHUBAPP_ID: ${{ secrets.GITHUBAPP_ID }}
      GITHUBAPP_PRIVATE_KEY: ${{ secrets.GITHUBAPP_PRIVATE_KEY }}
