name: renovate-schedule.yml
on:
  schedule:
    - cron: '0 3 * * 1-5'
  workflow_dispatch:

jobs:
  revonate:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/renovate
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
