name: "Authenticate to Amazon ECR in Cloud Platform"
description: "Authenticate to Amazon ECR in Cloud Platform"
inputs:
  ecr-region:
    description: AWS region for ECR (e.g. eu-west-2)
    required: true
  ecr-role-to-assume:
    description: AWS IAM role ARN to assume via OIDC for ECR
    required: true
outputs:
  ecr-registry:
    description: Amazon ECR registry URL prefix
    value: ${{ steps.login-ecr.outputs.registry }}

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.3.1
      with:
        aws-region: "${{ inputs.ecr-region }}"
        role-to-assume: "${{ inputs.ecr-role-to-assume }}"

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2.0.1
